defaults:
  - base_config
  - _self_

computing_resources:
  devices: 1
  workers: 1
  strategy: auto

global_seed: 42
checkpoint: null
default_root_dir: null

training_set: ???
validation_set: ???

training_parameters:
  learning_rate: 1e-5
  weight_decay: 0.
  warmup_epochs: 1
  epochs: 1000
  check_val_every_n_epoch: 50
  epoch_size: 320000
  lr_frequency: 1
  lr_interval: epoch

embedding_network:
  input_layer: 640
  nhead: 10
  num_layers: 6
  dim_feedforward: 1280
  hidden_layer: 640
  res_block_layers: 0
  pst_model_path: null

metadata: Default config
