defaults:
  - training_default
  - core_config
  - _self_

global_seed: 42
checkpoint: null
default_root_dir: null

training_set: ???
validation_set: ???

training_parameters:
  learning_rate: 1e-5
  weight_decay: 0.
  warmup_epochs: 2
  epochs: 1000
  check_val_every_n_epoch: 5
  epoch_size: 320000
  lr_frequency: 1
  lr_interval: epoch

metadata: Default config
